name: Validate Pyinstaller Build

on:
  push:
    branches:
      - "py_installer_gha_ci"

jobs:
  build:
    name: build-pyinstaller
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - run: chmod +x ./installer/pyinstaller/build-linux.sh
      - run: CI_OVERRIDE=1 ./installer/pyinstaller/build-linux.sh
      - run: ls -ltra
      - run: ls -ltra .build
      - run: ls -ltra .build/output
      - uses: actions/upload-artifact@v3
        with:
          name: pyinstaller-output
          path: .build/pyinstaller_output.log
      - uses: actions/upload-artifact@v3
        with:
          name: pyinstaller-warnings
          path: .build/src/build/samcli/warn-samcli.txt
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: pyinstaller-spec
          path: .build/src/__main__.spec